"""
Soak target list — manage the user's target vocabulary.

The core feature Dan asked for: a custom target word list
that can be changed on the fly. Targets are stored in the
IntensiveMorphDB with is_target=True. The list can be managed via:
- A plain text file (one lemma per line)
- Direct CLI commands (add/remove/list)
- The Anki browser (via fields/tags)
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

from .config import IntensiveMorphConfig
from .morphemizer import Morphemizer
from .models import LemmaState, IntensiveMorphDB, Stage


class TargetList:
    """
    Manages the set of words the user is targeting for learning.
    """

    def __init__(self, config: IntensiveMorphConfig, db: IntensiveMorphDB, morphemizer: Morphemizer):
        self.config = config
        self.db = db
        self.morphemizer = morphemizer

    # --- Core operations ---

    def get_targets(self) -> List[LemmaState]:
        """Get all current target lemmas."""
        return self.db.get_target_lemmas()

    def get_target_lemmas_set(self) -> Set[str]:
        """Get just the set of target lemma strings."""
        return {l.lemma for l in self.db.get_target_lemmas()}

    def add_target(self, word: str) -> Tuple[bool, str]:
        """
        Add a word to the target list.
        Word is automatically lemmatized.

        Returns (success, message).
        """
        # If it's a phrase (multiple words), just use it as-is as a lemma
        word = word.strip().lower()
        if not word:
            return False, "Empty word"

        # Lemmatize to get the base form
        lemmas = self.morphemizer.lemmatize(word)
        if lemmas:
            target_lemma = lemmas[0]
        else:
            target_lemma = word

        if self.db.add_target(target_lemma):
            return True, f"Added '{target_lemma}' as target word"
        else:
            return False, f"'{target_lemma}' is already a target word"

    def remove_target(self, word: str) -> Tuple[bool, str]:
        """
        Remove a word from the target list.
        Accepts surface form or lemma.
        """
        word = word.strip().lower()
        if not word:
            return False, "Empty word"

        # Try exact match first, then lemmatized
        if self.db.remove_target(word):
            return True, f"Removed '{word}' from target list"

        lemmas = self.morphemizer.lemmatize(word)
        if lemmas and lemmas[0] != word:
            if self.db.remove_target(lemmas[0]):
                return True, f"Removed '{lemmas[0]}' from target list"

        return False, f"'{word}' not found in target list"

    def list_targets(self) -> List[dict]:
        """Get target words with their current state for display."""
        targets = self.get_targets()
        return [
            {
                "lemma": t.lemma,
                "stage": t.stage.value,
                "score": round(t.score, 2),
                "appearances": t.appearances,
                "pass_rate": round(t.pass_rate, 2) if t.appearances > 0 else "-",
                "sentence_count": self.db.count_sentences_for_lemma(t.lemma),
            }
            for t in sorted(targets, key=lambda x: x.lemma)
        ]

    # --- File-based target lists ---

    def load_from_file(self, path: str | Path) -> Tuple[int, int]:
        """
        Load targets from a plain text file (one lemma per line).
        Comments start with #. Blank lines ignored.

        Returns (added_count, skipped_count).
        """
        path = Path(path)
        if not path.exists():
            return 0, 0

        added = 0
        skipped = 0

        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                word = line.strip()
                if not word or word.startswith("#"):
                    continue
                success, _ = self.add_target(word)
                if success:
                    added += 1
                else:
                    skipped += 1

        return added, skipped

    def save_to_file(self, path: str | Path) -> int:
        """Save current target list to a text file. Returns count saved."""
        targets = self.get_targets()
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)

        with open(path, "w", encoding="utf-8") as f:
            f.write(f"# Soak target words — {len(targets)} targets\n")
            f.write("# Generated by Soak target list manager\n\n")
            for t in sorted(targets, key=lambda x: x.lemma):
                f.write(f"{t.lemma}\n")

        return len(targets)

    # --- Batch operations ---

    def set_targets_from_list(self, lemmas: List[str]) -> int:
        """Replace entire target list with a list of lemmas."""
        return self.db.set_targets(lemmas)

    def clear_all_targets(self) -> int:
        """Remove all target entries. Returns count removed."""
        targets = self.get_targets()
        count = 0
        for t in targets:
            if self.db.remove_target(t.lemma):
                count += 1
        return count

    def import_from_sentence_pool(self, min_frequency: int = 2) -> int:
        """
        Scan all sentences in the DB and auto-add lemmas that appear
        frequently enough as targets. Useful for bootstrapping from
        imported text.
        """
        from collections import Counter

        all_sentences = self.db.get_all_sentences()
        lemma_counter: Counter = Counter()
        for sent in all_sentences:
            for lemma in sent.lemmas:
                lemma_counter[lemma] += 1

        added = 0
        for lemma, count in lemma_counter.items():
            if count >= min_frequency:
                success, _ = self.add_target(lemma)
                if success:
                    added += 1

        return added

    def get_recommendations(self, count: int = 10) -> List[str]:
        """
        Suggest the next best target words to add.
        Based on frequency in the sentence pool minus already-targeted words.
        """
        from collections import Counter

        all_sentences = self.db.get_all_sentences()
        already_targeted = self.get_target_lemmas_set()

        lemma_counter: Counter = Counter()
        for sent in all_sentences:
            for lemma in sent.lemmas:
                if lemma not in already_targeted:
                    lemma_counter[lemma] += 1

        return [lemma for lemma, _ in lemma_counter.most_common(count)]
